name: Update version in package.json
description: Automated version bump for npm packages.
author: 'Damien Sygusch'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: chevron-up
  color: blue
inputs:
  token:
    description: 'github token'
    default: ''
    required: true
outputs:
  update:
    description: Whether the version has update in the examined commits
